config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants do 
    resources :reviews, only: [ :new, :create, :show ]
  end
  resources :reviews, only: [  :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy
    validates :name, presence: true
    validates :phone_number, presence: true
    validates :address, presence: true
    validates :category, presence: true, inclusion: { in: %w(chinese italian japanese french belgian),
    message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  
  validates :content, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: [0,1,2,3,4,5],
    message: "%{value} is not a valid rating" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            redirect_to restaurant_path(@restaurant)
          else
            render :new
          end
    end


    def edit
        @restaurant = Restaurant.find(params[:id])
    end
    
    def show
        @restaurant = Restaurant.find(params[:id])
    end
    
    def update
        @restaurant = Restaurant.find(params[:id])
        @restaurant.update(restaurant_params)
        redirect_to restaurants_path(@restaurant)
    end

    

    def destroy
        @restaurant =Restaurant.find(params[:id])
        @restaurant.destroy
        redirect_to restaurants_path(@restaurant)
    end
    private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review.restaurant = @restaurant
        if @review.save
          redirect_to restaurant_path(@restaurant)
        else
          render :new
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to restaurant_path(@review.restaurant)
    end

    private
    def review_params
        params.require(:review).permit(:content, :rating)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Complet your new restaurant</h1>
<%=simple_form_for(@restaurant) do |f| %>
<div class="form-group">
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category%>
  <%= f.submit %>
  
<% end %>

<div class="btn btn-light"><%=link_to "Back to list", restaurants_path %></div>

app/views/restaurants/index.html.erb
<ul>
    <% @restaurants.each do |restaurant|%>

        <li><%=link_to restaurant.name, restaurant_path(restaurant) %> </li>
        <%= link_to restaurant_path(restaurant), method: :delete, data: { confirm: "Delete #{restaurant.name}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
           <% end %>
    <%end%>

</ul>

    
 
<div class="btn btn-light"><%=link_to "Add a new restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<h1>Complet your new restaurant</h1>
<%=simple_form_for(@restaurant) do |f| %>
<div class="form-group">
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category%>
  <%= f.submit %>
  
<% end %>

<div class="btn btn-light"><%=link_to "Back to list", restaurants_path %></div>

app/views/restaurants/show.html.erb
<div>
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.phone_number %></p>
<div class="btn btn-light"><%=link_to "Edit", edit_restaurant_path(@restaurant) %></div>
<div class="btn btn-light"><%=link_to "Back to list", restaurants_path %></div>
</div >


<ul class="list-group-item">
    <% @restaurant.reviews.each do |review|%>
    <li><%=review.content%>
    <%=review.rating%></li> 
    <% end %>
</ul>
    <%= link_to"right your review", new_restaurant_review_path(@restaurant)%>
 

app/views/reviews/destoy.html.erb
<li class="list-group-item">
      <%= review.content %>
      <%= link_to "Remove",
                  review_path(review),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </li>

app/views/reviews/new.html.erb
  <%= simple_form_for([ @restaurant, @review ]) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit review", class: "btn btn-primary"  %>
  <% end %>

app/views/reviews/show.html.erb
<%@restaurant.review.each do |review|%>
<li class = 'list_group_item'><%=review.content%><li>
<li class = 'list_group_item'><%=review.rating%><li>

<%end%> 